---
- name: Clean pre-install node
  become: true
  command: >
    rm -rf /usr/local/{lib/node{,/.npm,_modules},bin,share/man}/{npm*,node*,npx*,man1/node*} /usr/local/include/node

- name: Install node LTS
  become: false
  command: n lts
