---
- name: Install Node with n-install
  become: yes
  become_flags: -i
  become_user: runner
  block:
    - name: Install n-install w/ node LTS
      ansible.builtin.shell: >
        curl -sL https://git.io/n-install | bash -s -- -q
      args:
        executable: /bin/bash
        chdir: "$HOME"
        creates: yes